### Read category
GET http://localhost:5000/api/v2/category

### Read product
GET http://localhost:5000/api/v2/product/61526b1112ec817bb1a6cb5d

### Add user
POST http://localhost:5000/api/v2/user
Content-Type: application/json

{
    "fname": "Hendra",
    "lname": "Wijaya",
    "email": "hendra2.here@yahoo.com",
    "password": "aaaaaaaa"
}

### Check pin and delete pin
POST http://localhost:5000/api/v2/user/email-verification
Content-Type: application/json

{
    "otp": "432982",
    "email": "hendra1.here@yahoo.com"
}

### Get user for login
POST http://localhost:5000/api/v2/user/login
Content-Type: application/json

{
    "email": "hendra2.here@yahoo.com",
    "password": "aaaaaaasda"
}

### FInd user by email
GET http://localhost:5000/api/v2/user/hendra.here@yahoo.com