### Read category
GET http://localhost:5000/api/v2/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYTIuaGVyZUB5YWhvby5jb20iLCJpYXQiOjE2MzU5MDAwMDEsImV4cCI6MTYzNTkwMDkwMX0.HqtODEoSPatrjuywGjHzZFlYD_kD-8u5t3CAASel1AE

## --------------------------------------------------------------------------------- ##

### Read product
GET http://localhost:5000/api/v2/product/61526b1112ec817bb1a6cb5d

## --------------------------------------------------------------------------------- ##

### Add user
POST http://localhost:5000/api/v2/user
Content-Type: application/json

{
    "fname": "Hendra",
    "lname": "Wijaya",
    "email": "hendra2.here@yahoo.com",
    "password": "aaaaaaaa"
}

### Check pin and delete pin
POST http://localhost:5000/api/v2/user/email-verification
Content-Type: application/json

{
    "otp": "432982",
    "email": "hendra1.here@yahoo.com"
}

### Get user for login
POST http://localhost:5000/api/v2/user/login
Content-Type: application/json

{
    "email": "hendra2.here@yahoo.com",
    "password": "aaaaaaaa"
}

### FInd user by email for reset password purpose
GET http://localhost:5000/api/v2/user/hendra2.here@yahoo.com

### Update user password
PUT http://localhost:5000/api/v2/user
Content-Type: application/json

{
    "email": "hendra2.here@yahoo.com",
    "otp" : "256603232202848",
    "password" : "hendra1234"
}

### FInd user by token
GET http://localhost:5000/api/v2/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYTIuaGVyZUB5YWhvby5jb20iLCJpYXQiOjE2MzYzNDkyNDcsImV4cCI6MTYzNjM1MDE0N30.m4mumK1RaYibrClZs9rJJOJs2FxBXHO0oi6lsSY7Uj8

## --------------------------------------------------------------------------------- ##

### Request new access token 

GET http://localhost:5000/api/v2/session
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYTIuaGVyZUB5YWhvby5jb20iLCJpYXQiOjE2MzYzNTAzMTUsImV4cCI6MTYzODk0MjMxNX0.Bl_XHISuNlR1rZwvUvwirAcYl4qTzVTpF9A6_lE8yQk

## --------------------------------------------------------------------------------- ##

### Fetch all the payment options

GET http://localhost:5000/api/v2/paymentOpt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYTIuaGVyZUB5YWhvby5jb20iLCJpYXQiOjE2Mzc2MjMyMDEsImV4cCI6MTYzNzYyNDEwMX0.SpxIG5WPA2SOGL3kTM_a_UPAx4T34EvnIOyY9I0rS_0


## -------------------------------------------------------------------------------- ##

### Add order

POST http://localhost:5000/api/v2/order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmRyYTIuaGVyZUB5YWhvby5jb20iLCJpYXQiOjE2Mzc2MjMyMDEsImV4cCI6MTYzNzYyNDEwMX0.SpxIG5WPA2SOGL3kTM_a_UPAx4T34EvnIOyY9I0rS_0

{
"shippingAddressDetails": {
    "city": "dasdsa",
    "fname": "Hendra",
    "lname": "Wijaya",
    "postalCode": "dsas",
    "state": "dasdas", 
    "street": "2a WILLIS STREET",
    "unit": "dadas"
},

"cartDetails" : [
    {
        "images": "http://localhost:8000/img/products/banana11635139572987.png",
        "price": 5,
        "qty": 8,
        "slug": "banana",
        "title": "Banana",
        "_id": "6173c0f65cd3996a5b723848"
    },
    {
        "images": "http://localhost:8000/img/products/banana11635139572987.png",
        "price": 5,
        "qty": 8,
        "slug": "banana",
        "title": "Banana",
        "_id": "6173c0f65cd3996a5b723848"
    },
    {
        "images": "http://localhost:8000/img/products/banana11635139572987.png",
        "price": 5,
        "qty": 8,
        "slug": "banana",
        "title": "Banana",
        "_id": "6173c0f65cd3996a5b723848"
    }
],

"invoiceDetails": {
    "tax": 11.5,
    "total": 115,
    "totalNet": 103.5
},

"paymentDetails": {
    "method": "Pay by Bank ID",
    "totalPaid": 0,
    "transactionId": "00000001",
    "status": "pending"
},

"userDetails": {
    "email": "hendra2.here@yahoo.com",
    "fname": "Hendra",
    "lname": "Wijaya",
    "phone": "",
    "_id": "617f1b59144008514ae190e3"
}
}