### Read category
GET http://localhost:5000/api/v2/category

### Read product
GET http://localhost:5000/api/v2/product/61526b1112ec817bb1a6cb5d

### Add user
POST http://localhost:5000/api/v2/user
Content-Type: application/json

{
    "fname": "Hendra",
    "lname": "Wijaya",
    "email": "hendra10.here@yahoo.com",
    "password": "aaaaaaaa"
}
